# interfaces.py
from typing import Protocol

class InputSource(Protocol):
    def get_app(self) -> bytes: ...

class Transport(Protocol):
    def connect(self) -> None: ...
    def close(self) -> None: ...
    def send_app(self, app: bytes, mirror_over_tcp: bool = False) -> None: ...

__all__ = ["InputSource", "Transport"]
